// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { GeoPoint as __GeoPoint } from "./geo_point_type";

export type Tweet = {
  rowId: bigint,
  tweetId: string,
  content: string,
  username: string,
  location: __GeoPoint,
  createdAt: Timestamp,
  topic: string | undefined,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Tweet {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("rowId", AlgebraicType.createU64Type()),
      new ProductTypeElement("tweetId", AlgebraicType.createStringType()),
      new ProductTypeElement("content", AlgebraicType.createStringType()),
      new ProductTypeElement("username", AlgebraicType.createStringType()),
      new ProductTypeElement("location", __GeoPoint.getTypeScriptAlgebraicType()),
      new ProductTypeElement("createdAt", AlgebraicType.createTimestampType()),
      new ProductTypeElement("topic", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Tweet): void {
    Tweet.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Tweet {
    return Tweet.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


