// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { Tweet } from "./tweet_type";
import { GeoPoint as __GeoPoint } from "./geo_point_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `tweet`.
 *
 * Obtain a handle from the [`tweet`] property on [`RemoteTables`],
 * like `ctx.db.tweet`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.tweet.on_insert(...)`.
 */
export class TweetTableHandle {
  tableCache: TableCache<Tweet>;

  constructor(tableCache: TableCache<Tweet>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<Tweet> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `rowId` unique index on the table `tweet`,
   * which allows point queries on the field of the same name
   * via the [`TweetRowIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.tweet.rowId().find(...)`.
   *
   * Get a handle on the `rowId` unique index on the table `tweet`.
   */
  rowId = {
    // Find the subscribed row whose `rowId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): Tweet | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.rowId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: Tweet) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: Tweet) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: Tweet) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: Tweet) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: Tweet, newRow: Tweet) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: Tweet, newRow: Tweet) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
